name: Run ML Tests

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - main

jobs:
  test_ml:
    name: Test on Python 3.11
    runs-on: ubuntu-latest
    if: ((github.event_name == 'pull_request_review' && github.event.review.state == 'approved') || github.event_name == 'push')

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "6.0"
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipenv
          pipenv sync --dev --python $(which python)
          pipenv shell --fancy --python $(which python)
          pipenv run python -m pip install pytest

      - name: Run tests
        run: |
          cd machine-learning-client
          pipenv run python -m coverage run -m pytest
          pipenv run python -m coverage report --include=src/**/*.py --fail-under=80